### ISSUE TITLE
Can you give me some datasets?

### ISSUE THREAD

**Issue by itsagirl** [GRAP-UdL-AT/fruit_detection_in_LiDAR_pointClouds#1]
Thanks for your kindly share of  this method. But when I enter this web of http://www.grap.udl.cat/en/publications/KFuji_RGBDS_database.html
I can't download the dataset , so can you give me some data to run this method?Plz.

**Comment by Jordi-Gene-Mola** [comment]
Thank you for your interest. The dataset will be published in http://www.grap.udl.cat/en/publications/LFuji_air_dataset.html after the corresponding paper acceptance.

**Comment by Jordi-Gene-Mola** [comment]
Hi @itsagirl. The dataset is already available at  http://www.grap.udl.cat/en/publications/LFuji_air_dataset.html
